name: Java CI

on: [push]

jobs:

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run with Gradle
      run: gradle run

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run with Gradle
      run: gradle build
